"""LangGraph State definitions for the newsletter pipeline."""

from __future__ import annotations

from typing import TypedDict, Literal
from dataclasses import dataclass, field


class Article(TypedDict, total=False):
    url: str
    title: str
    snippet: str
    summary_kr: str
    source: str
    published_date: str
    collection_domain: str
    score: float
    tags: list[str]
    country: str
    # countries: list of country codes this article applies to.
    # For local articles: [country]. For global articles: ["GLOBAL"].
    # Populated by issue_builder; absent in earlier pipeline phases.
    countries: list[str]
    scope: str   # "local" | "global" | "other_country" — set by scorer
    sector: str  # 경쟁사활동 | 윤활유동향 | 전방산업동향 | 윤활유규제
    group_id: str | None
    title_kr: str
    score_sales: float
    score_country: float
    score_action: float
    related_sources: list
    url_valid: bool
    google_news_url: str


class AuditFeedback(TypedDict):
    passed: bool
    score: float
    issues: list[str]
    suggestions: list[str]


# ── Unified Issue (통합 발행물) ──────────────────────────────────────────────

class GlobalSection(TypedDict, total=False):
    """Articles that apply to all countries (scope == 'global'), deduped."""
    articles: list[Article]


class CountrySection(TypedDict, total=False):
    """Per-country section: local articles + LLM-generated content."""
    country: str
    articles: list[Article]         # scope=="local", deduplicated against GlobalSection
    insights: list[str]             # 5 items — generated by writer LLM call
    recommendations: list[str]     # 4 items — generated by writer LLM call
    kpi_data: dict                  # KPI metrics for this country


class UnifiedIssue(TypedDict, total=False):
    """Single structured issue object covering all countries.

    Rendered once; recipients get an email with (global + their country) sections.
    Web version exposes full tab UI via ?country=XX query param.
    """
    run_id: str
    date_str: str
    countries: list[str]                         # ordered; preserved from pipeline
    global_section: GlobalSection
    country_sections: dict[str, CountrySection]  # country_code -> section


# ─────────────────────────────────────────────────────────────────────────────


class NewsletterState(TypedDict, total=False):
    """Main state flowing through the LangGraph pipeline."""

    # Run configuration
    run_id: str
    countries: list[str]
    date_str: str
    days: int

    # Phase tracking
    current_phase: str
    phase_status: dict[str, str]  # phase_name -> "pending"|"running"|"done"|"failed"
    errors: list[str]

    # Phase 0.5: Keywords
    keywords: dict[str, list[str]]  # country -> keywords

    # Phase 1: Collection
    raw_articles: dict[str, list[Article]]  # country -> articles

    # Phase 1.5: Merged
    merged_articles: dict[str, list[Article]]

    # Phase 2: Scored
    scored_articles: dict[str, list[Article]]

    # Phase 2.5: Enriched
    enriched_articles: dict[str, list[Article]]

    # Phase 2.7: Grouped
    grouped_articles: dict[str, list[Article]]

    # Phase 3: Newsletter HTML (legacy — per-country HTML, kept for rollback)
    newsletters: dict[str, str]  # country -> html

    # Phase 3 (unified): Single structured issue object
    unified_issue: UnifiedIssue

    # Phase 3.5: Audit
    audit_iteration: int
    max_audit_iterations: int
    audit_feedback: dict[str, AuditFeedback]  # country -> feedback

    # Phase 4: Sending
    send_results: dict[str, bool]  # country -> success

    # KPI data (fetched before writing)
    kpi_data: dict[str, dict]  # country -> {exchange_rate, interest_rate, cpi, vehicle_reg}

    # SSE events
    events: list[dict]


# Node status constants
PHASE_NAMES = [
    "keywords",
    "collection",
    "merge",
    "scoring",
    "enrichment",
    "grouping",
    "kpi",
    "writing",
    "auditing",
    "sending",
]
